#right now we are only processing GET requests
from assets.colors import *
def check(string, sub_str): 
    if (string.find(sub_str) == -1): 
        print("trying harder")
        return False 
    else: 
        return True

import requests
def tags(url):
    list = ['a',
            'a2',
            'abbr',
            'acronym',
            'address',
            'animate',
            'animatemotion',
            'animatetransform',
            'applet',
            'area',
            'article',
            'aside',
            'audio',
            'audio2',
            'b',
            'base',
            'basefont',
            'bdi',
            'bdo',
            'bgsound',
            'big',
            'blink',
            'blockquote',
            'body',
            'br',
            'button',
            'canvas',
            'caption',
            'center',
            'cite',
            'code',
            'col',
            'colgroup',
            'command',
            'content',
            'custom tags',
            'data',
            'datalist',
            'dd',
            'del',
            'details',
            'dfn',
            'dialog',
            'dir',
            'discard',
            'div',
            'dl',
            'dt',
            'element',
            'em',
            'embed',
            'fieldset',
            'figcaption',
            'figure',
            'font',
            'footer',
            'form',
            'frame',
            'frameset',
            'h1',
            'head',
            'header',
            'hgroup',
            'hr',
            'html',
            'i',
            'iframe',
            'iframe2',
            'image',
            'image2',
            'image3',
            'img',
            'img2',
            'input',
            'input2',
            'input3',
            'input4',
            'ins',
            'isindex',
            'kbd',
            'keygen',
            'label',
            'legend',
            'li',
            'link',
            'listing',
            'main',
            'map',
            'mark',
            'marquee',
            'menu',
            'menuitem',
            'meta',
            'meter',
            'multicol',
            'nav',
            'nextid',
            'nobr',
            'noembed',
            'noframes',
            'noscript',
            'object',
            'ol',
            'optgroup',
            'option',
            'output',
            'p',
            'param',
            'picture',
            'plaintext',
            'pre',
            'progress',
            'q',
            'rb',
            'rp',
            'rt',
            'rtc',
            'ruby',
            's',
            'samp',
            'script',
            'section',
            'select',
            'set',
            'shadow',
            'slot',
            'small',
            'source',
            'spacer',
            'span',
            'strike',
            'strong',
            'style',
            'sub',
            'summary',
            'sup',
            'svg',
            'table',
            'tbody',
            'td',
            'template',
            'textarea',
            'tfoot',
            'th',
            'thead',
            'time',
            'title',
            'tr',
            'track',
            'tt',
            'u',
            'ul',
            'var',
            'video',
            'video2',
            'wbr',
            'xmp']
    allowed = []
    for i in list:
        payload = '1x2Y3z<'+i+'>1x2Y3z'
        url_new = url.replace('xsshere',payload)
        r = requests.get(url_new)
        final = r.content
        x = final.decode().split('1x2Y3z')
        check_status = check(x[1],i)
        if (check_status == True):
            print(Formatting.Dim+i+"tag is allowed"+Formatting.Reset)
            allowed.append(i)
    return allowed